version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/project/zip
    overwrite: yes
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user
  AfterAllowTraffic:
    - location: stop.sh
      timeout: 60
      runas: ec2-user